### ISSUE TITLE
New main header on Gigs Board does not work well on alpha.near.org

### ISSUE THREAD

**Issue by frol** [near/devgigsboard-widgets#61] opened 2023-03-24 18:35 UTC
**Describe the bug**

Our new top bar has invalid positioning [on alpha.near.org gateway](https://alpha.near.org/#/devgovgigs.near/widget/gigs-board.pages.Feed)

**To Reproduce**

1. Go to https://alpha.near.org/#/devgovgigs.near/widget/gigs-board.pages.Feed

**Expected behavior**

It should not float in the middle of the page, instead, it should be part of the top panel.

**Screenshots**

<img width="1749" alt="image" src="https://user-images.githubusercontent.com/304265/227610789-ea12370a-9c11-4555-ad22-e0eb7dac2ad0.png">

**Comment by ailisp** [comment] 2023-03-27 01:42
The root cause of the bug is:

- near social directly placed Gigs Board widget in the widget container:
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/13259400/227819439-df4277b0-c357-4d18-ad8b-e81a7d4e4a8e.png">

- near alpha place Gigs Board widget in a child div in the widget container:
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/13259400/227819858-69574f9b-d954-409b-8ed4-1020c984be5a.png">

- Due to the widget container has `overflow: hidden !important;`, the banner has to be `position: fixed`. None of `sticky`, `relative` or `absolute` can display the banner to be full width as page.

- `position: fixed` set the position of Gigs Board widget relative to it's original position. But the original position is different on near social and near alpha

Therefore I have two possible ways to fix this: 
1. Remove the extra div in the near alpha renderer. E.g. `return <div>...</div>` to `return <>...</>`
2. Introduce a css variable on near alpha. Introduce the same variable on near social but different value. Assume this variable is named `--widget-top-position`, in the DevGov Gigs widget we can set position according to this var.

I think there is no way to fix this issue on widget side. Either way need some changes on near alpha.

**Comment by ori-near** [comment] 2023-03-30 03:39
Hi @ailisp thank you for looking into this. It seems like in the short term we would need to compromise with not making the banner full page width. And instead have it fill just the widget container. But I think the design tradeoff is worth it to prevent this bug. Can you please proceed with fixing this bug, and we can try to reach out to the Alpha team to find a more elegant solution later?

**Comment by ailisp** [comment] 2023-03-30 07:46
@ori-near Sounds good. Made a quick non-full width version preview:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/13259400/228766065-046bdca1-0756-48a3-87bb-75860e2a905f.png">

Does it look okay? Any other adjustment you want on the design?

**Comment by ori-near** [comment] 2023-03-30 21:56
Hi @ailisp – I'm assuming I'm just looking at the header. Yes, please proceed if this will fix the bug. Thank you.

**Comment by ailisp** [comment] 2023-03-31 03:05
This is also fixed in #60

**Closed by ailisp** 2023-03-31 03:05 UTC
Labels: bug
