### ISSUE TITLE
alpha.near.org top panel rendering bug

### ISSUE THREAD

**Issue by nearmax** [near/devgigsboard-widgets#67] opened 2023-03-29 22:32 UTC
**Describe the bug**
The top panel is not positioned correctly when rendered on alpha.near.org. But it works correctly on near.social.

**To Reproduce**
1. Go to https://alpha.near.org/#/devgovgigs.near/widget/gigs-board.pages.Post?id=386
2. Scroll down
3. Observe that "Developer Governance" is the middle of the text.

**Expected behavior**
All of the text is below the panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/35039879/228682641-bb828e53-17d7-485c-9d45-a29082796d7c.png)

**Comment by ori-near** [comment] 2023-03-30 03:28
Hi @nearmax this is a duplicate of https://github.com/near/devgigsboard-widgets/issues/61, so closing this.

**Closed by ori-near** 2023-03-30 03:28 UTC
Labels: bug
